// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    return app.get("/", function(req, res) {
      return res.render("index", {
        title: "Alifbo | Learn Arabic by playing"
      });
    });
  };

}).call(this);
