// Generated by CoffeeScript 1.3.3
(function() {

  Parse.Cloud.beforeSave("ErrorLog", function(request, response) {
    var severity;
    severity = request.object.get("severity");
    if (severity !== "ERROR" && severity !== "WARNING" && severity !== "INFO") {
      request.object.set("severity", "ERROR");
    }
    return response.success();
  });

}).call(this);
